GET http://localhost:3000/
###
GET http://localhost:3000/users
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Nombre del usuario",
  "email": "correo@example.com",
  "password": "contraseña123"
}
###
GET http://localhost:3000/users/123
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGM2YzE3NjVlZWRlYTE0MWM0NDM1MDciLCJyb2xlIjoidXNlciIsImlhdCI6MTY5MDc1OTgyOSwiZXhwIjoxNjkwNzY3MDI5fQ.ScM9lyLHBFPGcbly_jJI1wxJrWSzDzWKKLOnCme1Gv8
###
PATCH http://localhost:3000/users/123
Content-Type: application/json

{
  "name": "Nuevo nombre del usuario"
}
###
DELETE http://localhost:3000/users/123
###
GET http://localhost:3000/auth
###
GET http://localhost:3000/auth/login
###
GET http://localhost:3000/auth/register
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "usuario1@example.com",
  "password": "contrasenia_segura"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Leo",
  "email": "usuario1@example.com",
  "password": "contrasenia_segura"
}





